### ISSUE TITLE
List with publications in which tobac is used? 

### ISSUE THREAD

**Issue by JuliaKukulies** [tobac-project/tobac#106]
From the 20 citations of the original tobac paper on google scholar, I count at least 6 publications in which tobac has been used as a main method. I think it could be good to document this somewhere and have an up-to-date list with publications that use tobac.

**Comment by freemansw1** [comment]
I think this is a great idea (as we discussed). A documentation page listing every publication would be a great way to do this, I think? We can start with a PR to the repo and then ping various groups to check the list. This is, of course, a moving target, but it will be helpful as we take tobac into the future.

**Comment by JuliaKukulies** [comment]
Yes, that sounds fab! Do you think that this is something for the [readthedocs page](https://tobac.readthedocs.io/en/latest/) or should we start with a simple .md in the repo?

**Comment by freemansw1** [comment]
I think this would be best for the readthedocs/auto-generated docs, as that will result in more people reading them.

**Comment by JuliaKukulies** [comment]
I have create a PR for this, but will wait until #150 is merged to submit it as it is dependent on the RTD updates.

Just a small note on your suggestion @w-k-jones : I have looked a bit into this and it seems like it will be smartest to keep our RTD page static and without any user interaction, because this would add quite a few complications and security issues for a very small benefit. So I guess it is not really worth the struggle. Instead we could ask users to submit a PR to add their reference or simply to contact and inform us. What do you think?

**Comment by JuliaKukulies** [comment]
@freemansw1 or should I commit this to #150 instead of opening a separate PR?

**Comment by freemansw1** [comment]
Sorry @JuliaKukulies, I missed this! I am happy for you to commit it to #150.

**Comment by JuliaKukulies** [comment]
All right, I am closing the issue as it is solved with the last commit to #150 -> https://tobac--150.org.readthedocs.build/en/150/
