### ISSUE TITLE
Pytables dependency removal

### ISSUE THREAD

**Issue by w-k-jones** [tobac-project/tobac#119]
Source code inspection for the conda-forge feedstock found that pytables is not referenced anywhere and could be removed as a dependency. Is this true, and if so should it be removed from both the conda-forge and local requirements?

**Comment by freemansw1** [comment]
I believe that `pytables` is (used to be?) required downstream by one of our dependencies (maybe HDF5 saving of pandas files?), but that's not a good reason for us to require it. By the same token, I don't think we actually use `cf_units` ourselves either (`iris` does require it). I'm in favor of removing both of these requirements.

**Comment by freemansw1** [comment]
I figured out why `pytables` is currently required. Reading and writing hdf5 from `pandas` requires `pytables` as an optional dependency. 

That said, I'm not opposed to removing `pytables` as a dependency, but we would probably want to move the tutorial notebooks to saving the `pandas` output as `pickle` or something. The `pandas`-generated HDF5 files are pretty much only readable by `pandas` anyway.

**Comment by freemansw1** [comment]
I'm going to tag this as v1.5 and will do this along with #196. We should probably also remove `cf-units` as a dependency given that we don't use it directly.

**Comment by freemansw1** [comment]
Resolved with #204
