### ISSUE TITLE
`black` version incompatibilities causing formatting to fail. 

### ISSUE THREAD

**Issue by freemansw1** [tobac-project/tobac#160]
I've had a few commits on PRs fail recently due to version incompatibilities with `black`. To resolve this, we should specify a version of `black` that we will use in the workflow. 

My suggestion is that we just use the first stable version, `22.6.0`. @JuliaKukulies since you set this up initially, what are your thoughts?

**Comment by JuliaKukulies** [comment]
@freemansw1 that sounds good! I can set up a PR to specify the `black` version in the workflow and update `CONTRIBUTING.md` accordingly
