### ISSUE TITLE
Resetting parameters in linking_trackpy

### ISSUE THREAD

**Issue by snilsn** [tobac-project/tobac#163]
I have been working a lot lately with `linking_trackpy()` for my notebook about linking, and I have a suggestion:

I think the values for `MAX_SUB_NET_SIZE` and `MAX_SUB_NET_SIZE_ADAPTIVE`, which are controlled by the `subnet_size` keyword, should be reset after each function call.

The values of these parameters are stored globally. Therefore, this can lead to undesired behavior if `linking_trackpy` is called multiple times.

**Comment by freemansw1** [comment]
Yes, completely agreed with this! I'd go as far to say that we should call this a bugfix, but I'm not sure how urgent it is... For now I've milestoned it for 1.4. Given that you fixed the original implementation of this, I'd be happy for you to submit a bugfix, or I can do that!

**Comment by snilsn** [comment]
I will do the bugfix!

Can I do this along with adding the exceptions for #164?

**Comment by freemansw1** [comment]
I am happy for you to do both bugfixes in the same PR, yes!

**Comment by freemansw1** [comment]
This has been resolved with #168
