### ISSUE TITLE
Setting a default value for adaptive_step

### ISSUE THREAD

**Issue by snilsn** [tobac-project/tobac#164]
Another suggestion originating from my work with `linking_trackpy()`:

I think the default value for `adaptive_step` should be changed from _None_ to _0.95_ like in the original trackpy implementation. As long as `adaptive_stop` is not specified it is not used, but if `adaptive_stop` is not None, it does make sense to use a reasonable value by default instead of _None_, because this causes a cryptic exception.

**Comment by freemansw1** [comment]
I would personally be more inclined to add a more clear error when setting either to `None` while giving the other a value. I think users should be deliberate when using it, but I am also open to other suggestions!

**Comment by snilsn** [comment]
That's the other option I had in mind. I guess it involves a bit more coding, but I can totally see your point about using the adaptive search consciously. So I would be happy with adding exceptions if only one of them is _None_.

**Comment by freemansw1** [comment]
This has been resolved by #168
