### ISSUE TITLE
Sort `threshold` in Feature Detection

### ISSUE THREAD

**Issue by freemansw1** [tobac-project/tobac#167]
In feature detection, we don't sort `threshold`, leading to different behavior depending on how the user has ordered things. Given that we know we want to go from less extreme to more extreme (and the user is required to include `target`), I think we should sort these. 

This comes from a conversation with Yuliya Selevich and Johnny Luo at CCNY

**Comment by JuliaKukulies** [comment]
Agreed, that is a good point and easy to fix.
