### ISSUE TITLE
different values for n_min_threshold dependent on thresholds 

### ISSUE THREAD

**Issue by JuliaKukulies** [tobac-project/tobac#18]
After some discussions, @freemansw1 and I came to the conclusion that would be useful and rather easy to allow different minimum areas for different thresholds in the multithreshold feature detection. More specifically, that would mean to make `n_min_threshold` a dict/list that has to have the same number of elements as the provided threshold values (see suggestion @freemansw1 below). 

The idea behind it is that more extreme threshold values often are inherently associated with a smaller areas (e.g. the convective core/ the region with highest rain rates/ the region with coldest cloud temperatures of a cloud system).

**Comment by freemansw1** [comment]
I think these are both excellent ideas. For 1, we could make `n_min_threshold` in `feature_detection_multithreshold_timestep` optionally a dict or list, with each threshold value assigned to a different number of minimum points. I think this would be a relatively easy change, although we would want to make sure to do some input validation to ensure that we have a n_min_threshold for each threshold value. 

For 2, this should be a relatively easy change to add and would be of value especially for those with large datasets. I can start working on a PR to add that once we eventually get #57 (and #60 ) merged.

**Comment by JuliaKukulies** [comment]
Great, that sounds good! Agree about your point on input validation. We could allow either a single value in which case `n_min_threshold ` will the same for all threshold values or a list/dict in which case it has to match the number of given thresholds. I can have a look at this.

**Comment by JuliaKukulies** [comment]
@freemansw1  are you working on point 2) now? Otherwise, I can start working on a PR or help with this, if needed. Related to the suggestion of saving descriptive statistics of the masked input data: Do you think it is a good idea to have a function to update the segmentation mask files based on additional criteria from these statistics? For example, if you want to filter out all tracked cells that have a precipitation maximum of > 30 mm/hr once during their lifetime, you can easily use the feature dataframe with the new statistics to apply a criterion like that. But you may also want to update your segmentation mask accordingly and kick out all candidates that do not fulfill that criterion. Useful or something the users should take care of themselves?

**Comment by JuliaKukulies** [comment]
@freemansw1 Just to follow up on this, since these are actually 2 issues: I understand it as if you are working on 2) now. I will have a look into 1). Are you planning on deriving the statistics within the feature detection itself or as a postprocessing step? I would guess that it would be more efficient to do that directly in the feature detection , but the advantage with postprocessing would be that the statistics can be derived from other input datasets (maybe starting with requiring the same grid) as well.

I also think it could be useful to have a method to update the segmentation mask based on additional criteria from these statistics. As of now, the segmentation mask still contains the features that are not linked over time and I think it would be desirable to quickly get a mask which only contains the linked (and eventually filtered based on additional criteria) features. What do you think?

**Comment by JuliaKukulies** [comment]
I am on this one for v1.5. PR will be ready by tomorrow or Friday!

**Comment by freemansw1** [comment]
Fantastic, looking forward to it!

**Comment by JuliaKukulies** [comment]
Has been solved with #208
