### ISSUE TITLE
Raise error if no search range parameter is specified

### ISSUE THREAD

**Issue by snilsn** [tobac-project/tobac#212]
We should raise a specific error if neither `v_max`, `d_max` nor `d_min` is provided in `linking_trackpy`.

**Comment by snilsn** [comment]
If nobody is opposed to that, I would like to use this issue as introduction (and the fix) to our workflow for my successor in early January.

**Comment by freemansw1** [comment]
I think that makes sense. Thanks for the bug report and plan, @snilsn. I'll wait to tag this with a milestone until we have a clearer idea of the v1.5 timetable.
