### ISSUE TITLE
Tutorials not compatible with tobac v1.4.0 release

### ISSUE THREAD

**Issue by gewitterblitz** [tobac-project/tobac#213]
Hi,

I am sure the developers are working on it but most tutorials or examples at `https://github.com/tobac-project/tobac-tutorials/blob/main/tutorials/` are no longer compatible with the current/latest release of tobac. 

For example, in the Example_Updraft_Tracking.ipynb notebook

> dxy,dt=tobac.utils.get_spacings(W_mid_max)

gives the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [50], line 1
----> 1 dxy,dt=tobac.utils.get_spacings(W_mid_max)

File /opt/anaconda3/envs/tracer/lib/python3.9/site-packages/tobac/utils.py:702, in get_spacings(field_in, grid_spacing, time_spacing)
    698 from copy import deepcopy
    700 # set horizontal grid spacing of input data
    701 # If cartesian x and y corrdinates are present, use these to determine dxy (vertical grid spacing used to transfer pixel distances to real distances):
--> 702 coord_names = [coord.name() for coord in field_in.coords]
    704 if (
    705     "projection_x_coordinate" in coord_names
    706     and "projection_y_coordinate" in coord_names
    707 ) and (grid_spacing is None):
    708     x_coord = deepcopy(field_in.coord("projection_x_coordinate"))

File /opt/anaconda3/envs/tracer/lib/python3.9/site-packages/tobac/utils.py:702, in <listcomp>(.0)
    698 from copy import deepcopy
    700 # set horizontal grid spacing of input data
    701 # If cartesian x and y corrdinates are present, use these to determine dxy (vertical grid spacing used to transfer pixel distances to real distances):
--> 702 coord_names = [coord.name() for coord in field_in.coords]
    704 if (
    705     "projection_x_coordinate" in coord_names
    706     and "projection_y_coordinate" in coord_names
    707 ) and (grid_spacing is None):
    708     x_coord = deepcopy(field_in.coord("projection_x_coordinate"))

AttributeError: 'str' object has no attribute 'name'
```

> Features=tobac.themes.tobac_v1.feature_detection_multithreshold(W_mid_max,dxy,**parameters_features)

gives the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [47], line 1
----> 1 Features=tobac.themes.tobac_v1.feature_detection_multithreshold(W_mid_max,dxy,**parameters_features)

AttributeError: module 'tobac' has no attribute 'themes'
```

and even if I use the correct module path for `feature_detection_multithreshold' e.g., 

>  Features=tobac.feature_detection_multithreshold(W_mid_max,dxy,**parameters_features)

it still throws this error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [48], line 1
----> 1 Features=tobac.feature_detection_multithreshold(W_mid_max,dxy,**parameters_features)

File /opt/anaconda3/envs/tracer/lib/python3.9/site-packages/tobac/feature_detection.py:624, in feature_detection_multithreshold(field_in, dxy, threshold, min_num, target, position_threshold, sigma_threshold, n_erosion_threshold, n_min_threshold, min_distance, feature_number_start, wavelength_filtering)
    621 list_features_timesteps = []
    623 # loop over timesteps for feature identification:
--> 624 data_time = field_in.slices_over("time")
    626 # if single threshold is put in as a single value, turn it into a list
    627 if type(threshold) in [int, float]:

File /opt/anaconda3/envs/tracer/lib/python3.9/site-packages/xarray/core/common.py:256, in AttrAccessMixin.__getattr__(self, name)
    254         with suppress(KeyError):
    255             return source[name]
--> 256 raise AttributeError(
    257     f"{type(self).__name__!r} object has no attribute {name!r}"
    258 )

AttributeError: 'DataArray' object has no attribute 'slices_over'
```

**Comment by freemansw1** [comment]
Thanks for the bug report. You're absolutely right that this is an issue, and one that we're working on as we transition from the v1.x structure to the v2.x structure. v2.x will feature support for xarray and for multiple feature detection and tracking methods, but will not be released until sometime next year and is not currently up-to-date with the work on v1.x (see #143). 

For now, we encourage users planning to use v1.x (which has the most active development currently) to look at the examples in the documentation (e.g., https://tobac.readthedocs.io/en/latest/feature_detection/index.html) and the examples in this repository: https://github.com/tobac-project/tobac/tree/main/examples . I've personally also made tutorials in the v1.x structure and made them public here: https://github.com/freemansw1/camp2ex-tobac-tutorial, but this isn't being actively updated and is not currently part of the broader tobac project.

**Comment by freemansw1** [comment]
I should note that we would also welcome contributions to either this repo or the tobac-tutorials repo! We're actively working toward a release of v1.5, which is planned to include support for tracking across periodic boundaries, and support for detecting features and tracking in 3D. v1.6 will be a "compatibility release" bridging the current gap that you have noticed between v1.x and v2.x. 

We have monthly dev meetings open to all, a slack server, and multiple mailing lists. Mailing list info is in our `README`, and if you have any issues, my email is in my profile.

**Comment by gewitterblitz** [comment]
Thanks, @freemansw1. I am mostly working with radar data for which you already have an example notebook but I can submit a tutorial notebook with my use case too, if it is useful.

**Comment by freemansw1** [comment]
Tagging @fsenf here as he's the primary maintainer of the tutorials repo.

**Comment by w-k-jones** [comment]
All the example notebooks were updated to the current version with the v1.4.1 release #233, which should resolve this issue. Please let us know if anything else comes up!
