### ISSUE TITLE
Update example notebooks in main repo so that they properly work with tobac v1.4 

### ISSUE THREAD

**Issue by JuliaKukulies** [tobac-project/tobac#215]
#### From discussion in  https://github.com/tobac-project/tobac/discussions/214:

Some small things have not been properly updated in the example notebooks for tobac v1.4: 

-  do  not `extrapolate ` parameter (see #165) -> this is not a superbig issue, since we at least raise a `NotImplementedError` now 
-  `key`  in `pd.to_hdf()` is a required parameter

**Comment by JuliaKukulies** [comment]
@snilsn maybe another practice issue for your successor? :)

**Comment by JuliaKukulies** [comment]
Note that I put this as a different issue than #213 since it concerns the example notebooks in the main tobac repo (not in the tutorial repo) that should be compatible with tobac v1.4

**Comment by snilsn** [comment]
@JuliaKukulies I think that's a good idea in order to get some first experiences with git and jupyter and some insights into the structure of tobac.

If this can wait until January, we can do it that way.

**Comment by freemansw1** [comment]
I think that this can wait! We can put it as 1.4.2 or 1.5.0 (or 1.5.1) depending on timing.

**Comment by freemansw1** [comment]
@lettlini I think this is another good issue for you to tackle, if you're up for it!

**Comment by lettlini** [comment]
Yes, of course. I will have a look at this

**Comment by w-k-jones** [comment]
I fixed some of these issues for OLR_tracking_model and OLR_tracking in #217 so they might not need editing any more. It would also be good to re-run the plots to resolve the issue raised in #231. Let me know if I can help

**Comment by lettlini** [comment]
After looking into the notebooks in `examples/` in both the `main` and `hotfix` branches, I found that the issues @JuliaKukulies mentioned seem to be fixed in the `hotfix` branch thanks to @w-k-jones.
The notebooks that weren't changed in #217 already had the `extrapolate` argument set to `0`.

**Comment by JuliaKukulies** [comment]
You are absolutely right @lettlini, seems like everything is fixed now.  I can also see that the key parameter was actually provided in all notebooks when `pd.to_hdf()` is called. To be honest, I do not remember why I put this second issue here. Might just have been something that I got wrong in a local version of the notebooks. 

But good point @w-k-jones to just re-run the notebooks and make a PR for that. Would you like to do that @lettlini ?

**Comment by lettlini** [comment]
As far as I know, there actually was a problem with `pd.to_hdf()` caused by the columns `hdim_1` and `hdim_2` appearing twice in a `DataFrame` (cf. #214). However, this wasn't related to the notebooks and has since been fixed by @w-k-jones in the `hotfix` branch (cf. #217).

Yes, of course I can take care of that.

**Comment by JuliaKukulies** [comment]
Yes, that is right. We realized the bug regarding the duplicate column names because `pd.to_hdf()` does not work when columns are double-defined. This was, however, not related to the key parameter, so I really do not know what I meant there :) 

Great, thank you so much for taking care of this!

**Comment by JuliaKukulies** [comment]
Closing this as the notebooks were re-run as part of the hotfix for v1.4 and the other issues were already solved by @w-k-jones in #217
