### ISSUE TITLE
v1.4.1 hotfix

### ISSUE THREAD

**Issue by w-k-jones** [tobac-project/tobac#219]
Not that the duplicate column name bug in #216 is fixed do we want to release a hotfix patch straight away, or are there other quick fixes that could also be added?

**Comment by JuliaKukulies** [comment]
Thank you @w-k-jones for fixing this so quickly! Should we add a unit test for the tracking (and maybe even feature detection and segmentation) to ensure that output data frames always have unique column names?  Otherwise, I am OK with releasing it right away.

**Comment by w-k-jones** [comment]
Probably sensible to add a few tests to check no variable names are duplicated and that the returned column names are the same as the original df

Also the CI test is failing the docker build for some reason, I'm not sure exactly why as the tests on the PR itself all ran successfully

**Comment by freemansw1** [comment]
My initial look at the Docker output leads me to believe that it is an issue with Numba and probably not a show-stopper, but I want us to debug some before release. 

I agree with @JuliaKukulies that adding tests for this would probably be a good idea before release. @w-k-jones do you want to do this, or do you want me to?

**Comment by w-k-jones** [comment]
I can write some tests for the tracking function. As far as I'm aware this is only a problem with the tracking function because of the workaround for a trackpy bug, however it would probably be good to test that coordinate names from the input field are being correctly used in the output for the detection and segmentation as well. On a related note, I've noticed that part of the problem with tracking was caused by using the mutable features argument rather than the copy, so I'll look into changing this to make sure that we aren't inadvertently modifying the features df in the tracking function.

**Comment by w-k-jones** [comment]
#227 adds new tests for feature detection and tracking as requesting, as well as a couple of other minor improvements

**Comment by freemansw1** [comment]
Once #227 is merged, I'm happy for us to release 1.4.1

**Comment by w-k-jones** [comment]
Now that #227 is merged, all that's left is to bump the version number and create the release, correct?

**Comment by freemansw1** [comment]
Yeah, I'll put in a release issue.

**Comment by freemansw1** [comment]
@w-k-jones do you want to do the release? I'm happy for you to, or I can. I've made the standard release checklist an issue at #234 .

**Comment by w-k-jones** [comment]
Happy to do this, will try and get it done today
