### ISSUE TITLE
Slow tracking when setting `time_cell_min` to exclude more cells

### ISSUE THREAD

**Issue by freemansw1** [tobac-project/tobac#225]
I'm working on tracking reasonably-large datasets (~3 million + features), and I seem to be running into a new performance bottleneck I have not seen before. Simply, as `time_cell_min` excludes more cells, tracking runs slower. 

Here are my parameters:

```
parameters_linking = {}
parameters_linking["method_linking"] = "predict"
parameters_linking["adaptive_stop"] = 0.2
parameters_linking["adaptive_step"] = 0.95
parameters_linking["extrapolate"] = 0
parameters_linking["order"] = 1
parameters_linking["subnetwork_size"] = 200
parameters_linking["memory"] = 2
parameters_linking["time_cell_min"] = 15 * 60
parameters_linking["method_linking"] = "predict"
parameters_linking["v_max"] = 30

```

As `time_cell_min` goes from `0` to `15 * 60`, run time for my small test dataset goes from ~55s to ~90s.

It seems that the slowdown comes from this line: https://github.com/tobac-project/tobac/blob/49c4c276b8ddf25318c199ddb6e55eef07e44636/tobac/tracking.py#L333 in tracking. My guess is that this should be a pretty easy fix; `loc` is very slow, especially on large datasets. 

Full `line_prof` outputs here: https://gist.github.com/freemansw1/cd8561b2ab755081819eaad12f7bc092

**Comment by w-k-jones** [comment]
I expect in particular that it's the looping over each cell individually (and then using both loc and elementwise comparison on the entire column) that's causing it to be so slow. This also explains why the slowdown is only noticeable when increasing time_cell_min, as this effectively increases the number of calls to the performance heavy part of the loop

A simple fix would be to store the id of the stub cells in a list or array during the loop, and then perform a single loc call to assign the unassigned cell values after the loop.

**Comment by freemansw1** [comment]
This has gotten resolved, with the (unintended?) merging of the changes in #226
