### ISSUE TITLE
Track file conversion to xarray dataset within merge_split.py leading to error

### ISSUE THREAD

**Issue by sgupta92** [tobac-project/tobac#239]
within merge_split.py, converting the track file (which was read as a dataframe) to an xarray dataset returns the following error with "first = track_groups.first()" - ValueError: dimensions () must have the same length as the number of data dimensions, ndim=1

This could be side stepped by commenting out "TRACK = TRACK.to_xarray()" but would mean the script must be adjusted since "first" is now a dataframe. For instance, "cells = first["cell"].values" must be replaced with "cells = first.index.values", and so on...

**Comment by freemansw1** [comment]
Looping in @kelcyno here. My guess is that this is in fact a bug. If it is, we may need to target a 1.4.2 release.

**Comment by kelcyno** [comment]
@sgupta92 Can you tell me more about the data you're using? Would you mind sharing the xarray output of your TRACK?

**Comment by sgupta92** [comment]
> @sgupta92 Can you tell me more about the data you're using? Would you mind sharing the xarray output of your TRACK?

I am tracking reflectivity features from an S-band radar. For input to the merge split function, I am using the output from linking_trackpy which was saved as an hdf file and read using pd.read_hdf. I'll email the track file.

**Comment by freemansw1** [comment]
> @freemansw1 I can work on adding a catch here for variables with type 'object'.

I think that's a good idea. We also need to fix the issue of interpolated coordinates sometimes coming out as the `object` dtype. That's a separate issue, though, and I'll open a new issue on that.

**Comment by w-k-jones** [comment]
This should be solved with the fix to 2d coordinate interpolation producing object dtypes in #251 , which will be released in the v1.4.2 hotfix. Please let us know if this problem re-occurs after that is fixed, and I'll re-open the issue
