### ISSUE TITLE
`ncells` gets same value for all features in one timestep

### ISSUE THREAD

**Issue by JuliaKukulies** [tobac-project/tobac#246]
Thanks to @laurapaccini who posted in #245  that `ncells` in the feature output from the segmentation do not always correspond to the number of grid cells associated with the feature in the segmentation mask. 

Eventually, I found the problem in the segmentation code, where we iterate over the different features in one time step, but assign only the value of `ncells` of the last feature to all features : 

https://github.com/tobac-project/tobac/blob/09b176b2037fe75ee79a2096d633e790579f02ef/tobac/segmentation.py#L267-L275

I double-checked this behavior in our example notebooks, which all show only one unique value of `ncells` per timestep, although there are multiple features detected in each timestep. 

This bug will be relatively easy to fix but should be done asap and preferably with a test making sure that this does not happen again. 

Since we are about to release `v1.5` maybe it suffices to include this in `v1.5`?  But I leave it to @w-k-jones and  @freemansw1 to judge if another hotfix is needed.

**Comment by freemansw1** [comment]
I'm inclined to release this as a 1.4.2 hotfix; I'd rather have a 1.4.x version that we know works available as we introduce the variety of new features in 1.5.0.

**Comment by JuliaKukulies** [comment]
True, that is a good point. I can take care of this

**Comment by JuliaKukulies** [comment]
This has been solved with #247 and will be released in `v1.4.2`
