### ISSUE TITLE
Segmentation sometimes results in ncells = 0 

### ISSUE THREAD

**Issue by JuliaKukulies** [tobac-project/tobac#25]
Hi again, 

a question concerning the segmentation and related parameters: 

I figured that some of my [tracked features](https://github.com/JuliaKukulies/mcs_tracking/blob/master/GPM_IMERG/example_precip_tracking_large_dataset.ipynb)  have _ncells_ = 0, but _num_ > 0 in specific timesteps. 

So first of all, just to make sure I got the difference between _num_ and _ncells_ right:
 _num_ refers to the nr of pixels of the feature linked to the tracked _cell_ ,whereas _ncells_ refers to the nr of pixels of the entire segment (which can include multiple features and additional connected pixels in which the _cell_ is embedded down to the segmentation threshold _V_segmentation_). Since I did not allow the tracking algorithm to miss features for one or more of timesteps (_memory_ = 0) and there obviously are tracked features in the affected timestep (visible in dataframe and original nc files), I really wonder why _ncells_ still turns to be 0 (and has corresponding 0 values in the segmentation mask) sometimes. 

I did not dig too much in the segmentation.py code, but it seems like this happens when the segmentation_mask_i is created through the watershed method. Could it be that timesteps where the area of the tracked features entirely coincides with the segment area, results in _ncells_ = 0 and an empty segmentation mask? 

I thought first that this was only a minor issue, since the tracked features are correctly added to the dataframe. However, it creates a difficulty when you want to use the segmentation mask as a mask for the tracked cell (e.g., in order to calculate the total rainfall in the area or similar). What you get is 0 values in some timesteps in the masks, even though a tracked feature is located at the position. 

Maybe I am thinking too complicated, so I would appreciate some words about _num_ and _ncells_ :) So again my question: How can it be that I get a tracked feature with _num_ > 0, but _ncells_ = 0 ? Also, I am not entirely sure, which of the identified features in an overlapping cloud object becomes the actual tracked feature which is added to the tracking dataframe (and which than determines _num_). I am aware of the fact that parent features are already deleted during the multi-threshold feature detection, but what about a cloud object/segment that contains multiple features next to each other?

**Comment by mheikenfeld** [comment]
Hi Julia,
thanks for reporting that issue. I have worked on a few performance enhancements and fixes for the segmentation over the last days, I will create a pull request for those changes tomorrow and will look into the issues that you are describing here in more detail!

**Comment by JuliaKukulies** [comment]
After our discussion in #52, I think this is resolved. This was not really a bug and it seems like there are cases, where no segmentation can happen, resulting hence in `ncells = 0`.  Any objections to closing this issue @freemansw1 ?

**Comment by freemansw1** [comment]
I am not opposed to closing this!
