### ISSUE TITLE
Jupyter notebooks not generating through CI

### ISSUE THREAD

**Issue by freemansw1** [tobac-project/tobac#286]
Opening to continue the discussion from #258. In the `RC_V1.5.0` branch, our CI does not work to regenerate our notebooks. Tagging this as an open issue to block v1.5 release until we either resolve by fixing the CI or by manually regenerating the notebooks.

**Comment by w-k-jones** [comment]
Following on from the previous discussion, I think we should manually regenerate the notebooks to avoid this becoming a blocking issue for the release. We can do this quickly when `RC_v1.5.0` is ready to be merged into `main`. It would be nice to solve this problem properly for the future

**Comment by lettlini** [comment]
@w-k-jones I fully agree with you.

**Comment by freemansw1** [comment]
@lettlini Do we need to disable the CI to avoid the notebooks getting wiped, or will the CI failing have the same effect? 

Actually, maybe better to do a PR to just remove the CI in the first place; not ideal for the red x to be on our commit for a release.

**Comment by lettlini** [comment]
@freemansw1 I think we should remove this workflow until we find a good solution on how it works with branch protection rules (see #290). I don't think the notebooks can be changed  in any way by the workflow since it cannot push to protected branches.
