### ISSUE TITLE
Does input field for the feature detection should be iris.cube.Cube?

### ISSUE THREAD

**Issue by wreckdump** [tobac-project/tobac#299]
It is possible to just pass numpy array (in the shape of 2D or 3D or 4D) into the feature detection fuctions such as `tobac.feature_detection.feature_detection_threshold`?

**Comment by w-k-jones** [comment]
Hi @wreckdump 

tobac needs information about the dimensions and coordinates of the input data, so a simple numpy array cannot be used. You can however turn your numpy array into an iris cube as per the example below:

```
from datetime import datetime, timedelta
import numpy as np
from iris.coords import DimCoord
from iris.cube import Cube

test_data = np.arange(3*4*6).reshape(3,4,6)

# Data at ten minute intervals
start_time = datetime(2000,1,1)
time_data = start_time + np.arange(data.shape[0]) * timedelta(minutes=10)
time_seconds = np.array([(td - datetime(1970, 1, 1, 0, 0)).total_seconds() for td in time_data])

time = DimCoord(
    time_seconds,
    standard_name="time",
    var_name="time",
    units="seconds since 1970-01-01 00:00",
)

# Data at 1km spacing
y = DimCoord(np.arange(data.shape[1])*1000, standard_name="projection_y_coordinate", var_name="y", units="m")
x = DimCoord(np.arange(data.shape[2])*1000, standard_name="projection_x_coordinate", var_name="x", units="m")

# Create iris cube, with time as the 0th dimension, y as the 1st dimension and x as the 2nd dimension
cube = Cube(data, var_name="test_data", dim_coords_and_dims=[(time, 0), (y, 1), (x,2)])

# Now do some things with tobac...
import tobac

dxy,dt=tobac.get_spacings(cube)

parameters_features={}
parameters_features['position_threshold']='weighted_diff'
parameters_features['sigma_threshold']=0.5
parameters_features['n_min_threshold']=4
parameters_features['target']='minimum'
parameters_features['threshold']=[5,6,7,8]

tobac.feature_detection_multithreshold(cube ,dxy, **parameters_features)
```

iris cubes are a pain to work with, and in future we will be switching to using xarray which will make data conversions a lot easier. You could already use xarray instead of iris to convert your data, as the example below:

```
import xarray as xr

dataarray = xr.DataArray(
    data, 
    dims=("time", "y", "x"), 
    coords={"time":time_data, "y":np.arange(data.shape[1])*1000, "x":np.arange(data.shape[2])*1000}
)

tobac.feature_detection_multithreshold(dataarray.to_iris(), dxy=1000, **parameters_features)
```

**Comment by wreckdump** [comment]
Thank you for your reply.

It seems that the input array, formatted for the iris datatype, contains the 'projection_y_coordinate' information. If I am using NETCDF data, does tobac require such information in the NETCDF variable description?

And for the x and y dimensions, it seems that tobac only supports 'meters' for their units. Is this correct? Does it also support degree, as in longitude and latitude, in the CF compliant units of 'degree_north' and 'degree_south'?

Thanks.

**Comment by w-k-jones** [comment]
If you're loading data from netcdf, have you tried using `iris.load(filename)` or `xarray.open_dataset(filename).to_iris()`?

tobac can support any sort of spatial dimensions, the only requirement is that it has a dimension called "time" and is on a regular grid. The requirement for units of meters is only for the `tobac.get_spacings` function to detect the grid spacing. You can use any other coordinate system, as long as you provide the grid spacing in meters to using the `dxy` keyword.

We're looking into better handling lat-lon and other non-cartesian grids in future

**Comment by wreckdump** [comment]
Yes. I was actually using `iris.load_cube`, as in one of the examples.
