### ISSUE TITLE
How do I import hdf5 file back into the code (in the example)

### ISSUE THREAD

**Issue by wreckdump** [tobac-project/tobac#302]
Provided examples saves intermittent freatures as `hdf` data. I would like to know how I can import these files back into the code. For example, the following code demonstrates how to save the `Features` into a `hdf5` data.

```
# Perform feature detection:
print('starting feature detection')
Features=tobac.feature_detection_multithreshold(OLR,dxy, **parameters_features)
Features.to_hdf(savedir / 'Features.h5', 'table')
print('feature detection performed and saved')
```
But, the content after this part of the code does not show how to import the saved data back into the code. Did I miss it?

I tried using `tobac.iris_cube` for it but I get `no cubes found` error. Could you please add this into the example?

Thanks.

**Comment by w-k-jones** [comment]
`hdf` data is used to save pandas dataframes. You can load these again using `pandas.read_hdf`

See: https://pandas.pydata.org/docs/reference/api/pandas.read_hdf.html

**Comment by wreckdump** [comment]
Ahh. Okay. Thank you.

Another related question. Is there a particular reason on saving `Mask_OLR` as `netcdf` file and saving `Features` as `hdf5` in the example? Would it be fine to save everything in the same file format?

```
# Perform segmentation and save results:
print('Starting segmentation based on OLR.')
Mask_OLR,Features_OLR=tobac.segmentation_2D(Features,OLR,dxy,**parameters_segmentation)
print('segmentation OLR performed, start saving results to files')
iris.save([Mask_OLR], savedir / 'Mask_Segmentation_OLR.nc', zlib=True, complevel=4)                
Features_OLR.to_hdf(savedir / 'Features_OLR.h5', 'table')
print('segmentation OLR performed and saved')
```

And in case of importing the `netcdf` file back into the code, can I use `iris.load` or `iris.load_cube` ?

**Comment by w-k-jones** [comment]
At present tobac uses two different data structures:

- Tabular data is produced by feature detection and segmentation and is stored as pandas dataframes. This data is saved as hdf, and read using `pandas.read_hdf`

- Gridded data is used as the input to feature detection and segmentation and produced as output by segmentation. These are stored as iris cubes, are saved as netcdf format and read using `iris.load`.

At present, these are separate and not compatible, so you can't save as one and read as another. Our next major development will be a switch to xarray which can hold both data types at once and save/read to a number of formats including netcdf

`iris.load` is a bit more general than `iris.load_cube`, so it's generally the best way to go unless you know you need load_cube

**Comment by wreckdump** [comment]
Thank you.
