### ISSUE TITLE
How to let tobac know fill_value in the netcdf file?

### ISSUE THREAD

**Issue by wreckdump** [tobac-project/tobac#331]
I have an input file that has weird areas where their values are are set as -9999.0, as a fill_value for netcdf (see attached picture). The value -9999.0 is supposted to be taken as NaN value in python (or in any netcdf related softwares) so that it should be ignored.

`Iris` module is reading the netcdf file without applying the mask (fill_value of -9999.0), and tobac does not seem to know this. Is there a way to tell tobac not to consider a specific value so that it would ignore the fill_value?

![gem scrsht](https://github.com/tobac-project/tobac/assets/26279723/8fb35227-5f13-4846-bbaf-ee799b728b33)

**Comment by JuliaKukulies** [comment]
Tobac does not have a specific function to define the fill value in the input data. 

Usually it is best when the fill value is defined in the loaded dataset because you might want to keep that information for other operations. Does the netCDF you are opening has a properly define fill value? If not, you could change it using `xarray` or `NCO/CDO` (https://code.mpimet.mpg.de/boards/2/topics/3565). 

Alternatively you can also set the fill value of the data attribute of your iris cube (https://scitools-iris.readthedocs.io/en/latest/generated/api/iris.cube.html#iris.cube.Cube ) or simply change the data values that are `-9999.0` to `np.nan`.

**Comment by wreckdump** [comment]
Um... so I guess `iris` is correctly handling the `fill_value` as `np.nan`. But for some reason, `tobac` is treating `fill_value` areas as valid data points.

example data values of iris data cube
```
[[[-- -- -- ... 291.15032958984375 292.7417297363281 291.6527404785156]
  [-- -- -- ... 293.0906982421875 292.35272216796875 291.66082763671875]
  [-- -- -- ... 294.3814392089844 293.40570068359375 292.3965759277344]
  ...
  [312.0113220214844 310.80511474609375 309.0226135253906 ...
   293.8000793457031 291.7395935058594 295.8691101074219]
  [311.8231201171875 310.74249267578125 309.9149169921875 ...
   294.0130615234375 289.27911376953125 295.1790466308594]
  [309.64208984375 310.0537414550781 309.95196533203125 ...
   295.5054626464844 294.7171936035156 293.8650207519531]]

 [[-- -- -- ... 282.6540222167969 284.57452392578125 284.930419921875]
  [-- -- -- ... 285.3166809082031 285.3265686035156 285.5889892578125]
  [-- -- -- ... 287.7415466308594 287.42376708984375 287.1201477050781]
  ...
  [314.2368469238281 313.30059814453125 311.5663757324219 ...
   290.7585144042969 294.0787048339844 295.6382751464844]
  [314.0061950683594 313.3076171875 312.81201171875 ...
   294.6658020019531 293.7174072265625 294.44140625]
  [311.9427185058594 312.5367736816406 312.5076904296875 ...
   295.6319580078125 291.3963317871094 294.3623352050781]]

 [[-- -- -- ... 276.4613037109375 278.7796936035156 277.3859558105469]
  [-- -- -- ... 281.166748046875 280.1023864746094 280.9094543457031]
  [-- -- -- ... 282.4347229003906 282.95556640625 282.96893310546875]
  ...
  [313.38421630859375 312.5172119140625 311.1562194824219 ...
   292.87835693359375 294.84246826171875 295.73822021484375]
  [312.95501708984375 312.3735046386719 312.12713623046875 ...
   294.57147216796875 291.1443786621094 294.7926940917969]
  [311.0019226074219 311.48681640625 311.5829162597656 ...
   291.383544921875 290.3877868652344 295.3729553222656]]

 ...

 [[-- -- -- ... 233.54656982421875 234.6104278564453 234.9866485595703]
  [-- -- -- ... 235.58985900878906 236.42100524902344 237.68792724609375]
  [-- -- -- ... 238.05616760253906 239.93711853027344 241.58656311035156]
  ...
  [297.8957214355469 297.6215515136719 297.2995910644531 ...
   294.03741455078125 291.20440673828125 288.67352294921875]
  [296.8657531738281 296.35345458984375 296.36761474609375 ...
   294.6901550292969 293.8526916503906 291.6624755859375]
  [295.7127380371094 294.68377685546875 294.71417236328125 ...
   294.0294189453125 293.06298828125 292.8242492675781]]

 [[-- -- -- ... 230.9896240234375 231.2681427001953 230.94229125976562]
  [-- -- -- ... 232.37928771972656 232.92230224609375 233.62347412109375]
  [-- -- -- ... 235.9056854248047 237.6470184326172 239.11048889160156]
  ...
  [297.3628234863281 297.5378723144531 296.7164611816406 ...
   288.27001953125 286.6835632324219 287.86566162109375]
  [296.6050109863281 296.4112548828125 296.2220458984375 ...
   289.83734130859375 288.0789794921875 288.4068298339844]
  [296.14251708984375 294.9483337402344 294.8514709472656 ...
   293.21221923828125 291.1327209472656 291.2752990722656]]

 [[-- -- -- ... 235.43954467773438 236.74880981445312 235.2426300048828]
  [-- -- -- ... 240.84776306152344 241.21453857421875 239.3301544189453]
  [-- -- -- ... 242.08401489257812 242.58143615722656 241.98269653320312]
  ...
  [299.0758056640625 297.7485046386719 295.3299560546875 ...
   288.3941650390625 290.4830627441406 292.8115234375]
  [299.1620178222656 298.03948974609375 296.3911437988281 ...
   289.1743469238281 291.45989990234375 292.3090515136719]
  [298.94830322265625 297.6885986328125 296.9638977050781 ...
   288.1587829589844 288.1894226074219 289.40325927734375]]]
```

As you can see `np.nan` values are shown as `--`. `tobac` should ignore the `np.nan`, right?

And, this is one of the frames of the tracking results, showing the center of the detected feature, marked as  yellow `x`, on top of the brightness temperature field.
![gem trk weird](https://github.com/tobac-project/tobac/assets/26279723/b721ccfe-84db-4b26-aefb-39930317cae6)

**Comment by freemansw1** [comment]
I think `iris` is making it a masked array rather than assigning them `np.nan`. You may need to go and assign manually `np.nan`. Switching to `xarray` is on our roadmap for this year, which should lessen these headaches.

**Comment by wreckdump** [comment]
> I think `iris` is making it a masked array rather than assigning them `np.nan`. You may need to go and assign manually `np.nan`. Switching to `xarray` is on our roadmap for this year, which should lessen these headaches.

So... tobac is picking up masked elements for the feature detection? I am confused...

Looking at the `feature_detection_threshold()`
```
    # if looking for minima, set values above threshold to 0 and scale by data minimum:
    if target == "maximum":
        mask = data_i >= threshold
        # if looking for minima, set values above threshold to 0 and scale by data minimum:
    elif target == "minimum":
        mask = data_i <= threshold
```

If I understand it correctly, above lines are thresholding the value and generating the mask for the subsequent operations. Example data that I have posted shows the fill_values as masked values, and these are basically passed on to the `feature_detection_threshold()`. So, does this mean `mask = data_i >= threshold` or `mask = data_i <= threshold` is somehow converting masked arrays back into fill_value (which is -9999.0, and I am using 'minimum' option for thresholding) ?

**Comment by freemansw1** [comment]
My guess is that yes, either *tobac*, Iris, or scikit-image is not properly handling the masked array.

**Comment by wreckdump** [comment]
Okay. Thank you for your reply.
