### ISSUE TITLE
Changed behavior for stubs parameter in linking

### ISSUE THREAD

**Issue by fsenf** [tobac-project/tobac#338]
In the progress for back-integrating tutorials into the examples folder I discovered a change in the way linking handles the stubs parameter. I am not sure if this is a bug and the wanted change:

Here is the call of the notebook cell 

```python 
track = tobac.linking_trackpy(
    features, data, dt=dt, dxy=dxy, v_max=100, stubs=50
)
``` 
in In [49], https://github.com/fsenf/tobac/blob/backintegration_of_tutorials/examples/Basics/Methods-and-Parameters-for-Linking.ipynb

This images results
![grafik](https://github.com/tobac-project/tobac/assets/43379813/358120c1-3457-4e75-909c-48535f542512)

However, I expected this one:
![grafik](https://github.com/tobac-project/tobac/assets/43379813/cfbf42aa-28b3-4eae-9f84-fb40177c7d58)

see In [17], https://github.com/tobac-project/tobac-tutorials/blob/main/tutorials/Basics/Methods-and-Parameters-for-Linking.ipynb

Any idea?

**Comment by w-k-jones** [comment]
Problem is with the groupby loop:
```
for i, cell_track in track.groupby("cell"):
    cell_track.plot(...
```

This will loop over every value for "cell", including the "stub" value (-1 in this case), which will collect all stub features into a single track (hence the jumping back and forth between the two line). Easiest solution is just to skip over the stub value:

```
for i, cell_track in track.groupby("cell"):
    if i !-= -1:
        cell_track.plot(
            x="projection_x_coordinate",
            y="projection_y_coordinate",
            ax=ax,
            marker="o",
            alpha=0.2,
            label="cell {0}".format(int(i)),
        )
```

**Comment by freemansw1** [comment]
My guess is that Pandas groupby doesn't put `nan` values into a group, so when we switched to `-1` as the default for untracked cells, there is now a `-1` group. 

As an aside, we should probably rename `stubs`. Not a super helpful parameter name.

**Comment by fsenf** [comment]
Thank you for the feedback! Now I remember that the behavior of untracked cells was changed. E.g. #121 discussed that map plots changed because of the change in untracked cell handling.

I will modify the respective notebook in #334 such that this aspect get a small explanation.
