### ISSUE TITLE
Sort order bug in `test_trackpy_predict`

### ISSUE THREAD

**Issue by w-k-jones** [tobac-project/tobac#342]
The `test_trackpy_predict` unit test in `test_tracking.py` creates a dataframe with non-unique index values, which can result in errors on some systems. This is currently blocking the v1.5.1 release on conda, so is a pretty big issue

This also links to #319 and general testing improvements

**Comment by JuliaKukulies** [comment]
I created a PR #342 which hopefully fixes this? But yes, you are right that we should also prioritize general testing improvements for the next release, including testing on different systems.

**Comment by freemansw1** [comment]
I'm all for increased testing, but as always it's a trade in how we spend our time. Some of the increased testing robustness will come naturally through the xarray transition and the need to ensure results are consistent.
