### ISSUE TITLE
Example notebook downloads not working because zenodo file paths have changed... 

### ISSUE THREAD

**Issue by w-k-jones** [tobac-project/tobac#355]
As part of Zenodo's recent (problematic) updates, the path to archived files has changed from `https://zenodo.org/record/...` to `https://zenodo.org/records/...`. As a result we need to update all the original notebooks to fix this change. At present this issue is causing the notebook CI to fail

**Comment by freemansw1** [comment]
That's an extremely problematic change from something that is supposed to be "permanent"!

**Comment by w-k-jones** [comment]
Fixed in #357
