### ISSUE TITLE
Release 1.5.2

### ISSUE THREAD

**Issue by JuliaKukulies** [tobac-project/tobac#363]
We are almost ready for the next release. Here is the checklist:

- [x] Re-run notebooks and commit updates to the repository 
- [x]  Bump version in __init__.py 
- [x]  Add changelog 
- [x]  Merge RC_v1.5.x into main 
- [ ]  Delete RC_v1.5.x branch
- [x]  Create release
- [x]  Push release to conda-forge
- [x]  E-mail tobac mailing list

**Comment by freemansw1** [comment]
Do we want to include #362 in 1.5.2? Happy either way...

**Comment by freemansw1** [comment]
I also think we should do #347 before release

**Comment by JuliaKukulies** [comment]
Agreed, I think we can figure out these three PRs/issues before the next release. Added that to the check list!

**Comment by fsenf** [comment]
Hej all, could "Adding checklists for the issue tracker" #358 be considered as part of the v1.5.2 release? @fziegner has nearly finished this PR.

**Comment by fsenf** [comment]
I further added  "Introducing pylint in our workflow" #278 to the milestone list for v1.5.2. This work is also more than ready ;-)

**Comment by w-k-jones** [comment]
> Hej all, could "Adding checklists for the issue tracker" #358 be considered as part of the v1.5.2 release? @fziegner has nearly finished this PR.

We can also merge directly into `main` outside of a release, but I'm happy to get it in for v1.5.2 as well. Let me know when it's ready and I'll provide a review :)

**Comment by w-k-jones** [comment]
Version number, changelog and notebooks updates in #381

**Comment by w-k-jones** [comment]
Well, that ended up being mildly painful, but v1.5.2 is now live 🎉
