### ISSUE TITLE
Possible reference before assignment in bulk statistics?

### ISSUE THREAD

**Issue by freemansw1** [tobac-project/tobac#364]
In working on the new windows bug discovered in #353, I'm digging into `bulk_statistics.py/get_statistics_from_mask`. In looking at this line:  
https://github.com/tobac-project/tobac/blob/5f096e3e66da07cfd48a6a4588b993fc1263a0c2/tobac/utils/bulk_statistics.py#L201

it appears that there should be another loop for field? I'm not that familiar with this code though, so tagging @JuliaKukulies .

**Comment by w-k-jones** [comment]
Good catch! It'll be using the last `field` array from the loop at L185. Should be a quick fix to update to a generator, I'll do that now

**Comment by JuliaKukulies** [comment]
Good catch @freemansw1 and thank you so much for taking care of this, @w-k-jones !

**Comment by freemansw1** [comment]
Closing with #368 being merged
