### ISSUE TITLE
`features` parameter in bulk statistics is required as a keyword but has no default value

### ISSUE THREAD

**Issue by w-k-jones** [tobac-project/tobac#369]
Because the `features` parameter comes after `*fields` in `get_statistics_from_mask`, it is required to be passed as a keyword despite not having a default value. I think it would be best to resolve this by changing the parameter order so that `features` is passed as an argument before `*fields`. Would be best to do this before releasing `v1.5.2`

**Comment by JuliaKukulies** [comment]
Good point @w-k-jones! Will change this after merging #368

**Comment by w-k-jones** [comment]
I could also make the change as part of #368 

Would it also make sense to change the order of inputs to `get_statistics_from_mask` to `features`, `segments`, `*fields` in order to keep a consistent ordering with other tobac functions?

**Comment by JuliaKukulies** [comment]
> I could also make the change as part of #368
> 
> Would it also make sense to change the order of inputs to `get_statistics_from_mask` to `features`, `segments`, `*fields` in order to keep a consistent ordering with other tobac functions?

I think it would make sense, agreed! That would be great if you could just change that as part of #368

**Comment by w-k-jones** [comment]
Closed with #368
