### ISSUE TITLE
`RC_v1.5.x` Notebook CI failing

### ISSUE THREAD

**Issue by freemansw1** [tobac-project/tobac#370]
The notebook CI seems to be failing on the `RC_v1.5.x` branch. Haven't yet had the time to dig into why, but wanted to note. Could be a blocking issue for 1.5.2 release.

**Comment by w-k-jones** [comment]
I've fixed this issue as part of #368 :)

**Comment by JuliaKukulies** [comment]
Thank you both for detecting and fixing this issue

**Comment by freemansw1** [comment]
Closing with #368 being merged.
