### ISSUE TITLE
PBC dist_func not used for predictive tracking

### ISSUE THREAD

**Issue by w-k-jones** [tobac-project/tobac#375]
For predictive tracking, the dist_func keyword (used for the PBC distance calculation) is commented out. Can this be safely re-enabled? It seems to be working fine for me locally, and correctly tracks cells across periodic boundaries when uncommented

https://github.com/tobac-project/tobac/blob/f1d3a4ed4690dde9df954b0aff11d79cf6ba6955/tobac/tracking.py#L391

**Comment by w-k-jones** [comment]
@freemansw1 This was commented out as part of #209, I guess was this part of separating the 3D and PBC additions and it never got re-added with the PBCs?

**Comment by freemansw1** [comment]
> @freemansw1 This was commented out as part of #209, I guess was this part of separating the 3D and PBC additions and it never got re-added with the PBCs?

This seems likely. We can do a PR to uncomment.

**Comment by w-k-jones** [comment]
Resolved by #376
