### ISSUE TITLE
Add "box" seeding to segmentation documentation

### ISSUE THREAD

**Issue by w-k-jones** [tobac-project/tobac#399]
At present, the [documentation for segmentation](https://tobac.readthedocs.io/en/latest/segmentation.html) does not mention the box seeding option. As this is both an important addition as part of the v1.5 release, and probably the best practice for 3D segmentation we should aim to provide some documentation and possibly a comparison between box and column seeding

**Comment by freemansw1** [comment]
New PR #406 will address this.
