### ISSUE TITLE
Update `get_spacings` to allow xarray input

### ISSUE THREAD

**Issue by w-k-jones** [tobac-project/tobac#407]
Get spacings function currently only allows iris cube input, we should add the dataarray -> cube decorator to allow xarray input

https://github.com/tobac-project/tobac/blob/ed4c4bfc748582c18122d769843296c6125b6dd4/tobac/utils/general.py#L369

* [x] Have you searched the issue tracker for the same problem?
* [x] Have you checked if you're using the latest version? If not, which version are you using?
* [x] Have you mentioned the steps to reproduce the issue?
* [x] Have you, if applicable, included error messages?

**Comment by fsenf** [comment]
We have this functionality already in #334 waiting for approval by @w-k-jones and @fziegner . I am going to close to issue - hope that is fine for you.
