### ISSUE TITLE
Example notebooks need to be become visible on our RTD page

### ISSUE THREAD

**Issue by fsenf** [tobac-project/tobac#409]
* [x] Have you searched the issue tracker for the same problem?
* [x] Have you checked if you're using the latest version? If not, which version are you using?
* [x] Have you mentioned the steps to reproduce the issue?
* [x] Have you, if applicable, included error messages?

After #334 is done, `index.rst` needs to be modified such that examples are rendered on readthedocs (RTD) and therefore become visible. 

Typically, sphinx rendering only sees things below its root dir which is `./doc` in our case. Maybe one solution could be include a symbolic link there

i.e.

```bash
cd doc
ln -s ../examples .

# and then git it
```

**Comment by w-k-jones** [comment]
Closed with #411
