### ISSUE TITLE
Thumbnails for Notebook Gallery Got Lost

### ISSUE THREAD

**Issue by fsenf** [tobac-project/tobac#426]
* [x] Have you searched the issue tracker for the same problem?
* [x] Have you checked if you're using the latest version? If not, which version are you using?
* [x] Have you mentioned the steps to reproduce the issue?
* [x] Have you, if applicable, included error messages?

It is a bit tricky to selected cool images for the notebook gallery. By default, the gallery plugin is selecting the last image in the notebook, but this looks often similar and is sometime not the pretties ....

To change this, I set meta data tags within the notebooks like this:

```json
       "tags": [
     "nbsphinx-thumbnail"
    ]
```

in this commit: https://github.com/tobac-project/tobac/pull/411/commits/e28d4c3af4b181bed2fbcbf0bfdd11776cc41dc8

The tags were somehow lost in the code development process and it shows that a smarter way of selecting thumbnails for the gallery is needed.

Maybe we should have a look at other python packages like https://docs.xarray.dev/en/stable/gallery.html

**Comment by w-k-jones** [comment]
I think this happened because the code to regenerate the notebooks removes all output cells before running them. We will have to check if there is a way to preserve the metadata tags when doing this

**Comment by freemansw1** [comment]
Fixed with #428
