### ISSUE TITLE
Code Coverage CI consistently fails

### ISSUE THREAD

**Issue by freemansw1** [tobac-project/tobac#435]
It seems that our `codecov.io` CI action is now consistently failing. I've followed the troubleshooting steps and have updated our `CODECOV_TOKEN` in the GitHub secrets, which hopefully helps, but I'm putting this as an issue so that we track it. 

* [x] Have you searched the issue tracker for the same problem?
* [x] Have you checked if you're using the latest version? If not, which version are you using?
* [x] Have you mentioned the steps to reproduce the issue?
* [x] Have you, if applicable, included error messages?

**Comment by w-k-jones** [comment]
Fixed with #436.
