### ISSUE TITLE
Input fields of bulk statistics have to have coordinates 

### ISSUE THREAD

**Issue by JuliaKukulies** [tobac-project/tobac#447]
While the documentation of the bulk statistics suggests that the input field(s) the statistics are calculated from should be a `np.ndrarray`, but this does actually not work with our current implementation because we leverage the `field.coords` and `field.time `attribute in l. 295: 

https://github.com/tobac-project/tobac/blob/698d53bf019de6542056272c01d6a472caaf2c30/tobac/utils/bulk_statistics.py#L291-L296

This should be fixed by other updating the documentation or require that `fields` is an `xr.DataArray` (or iris so that it will be converted to the latter). Any thoughts what is better? 

* [x] Have you searched the issue tracker for the same problem?
* [x] Have you checked if you're using the latest version? If not, which version are you using?
* [x] Have you mentioned the steps to reproduce the issue?

**Comment by w-k-jones** [comment]
Resolved in #448
