### ISSUE TITLE
calculate_area

### ISSUE THREAD

**Issue by huangynj** [tobac-project/tobac#49]
https://github.com/climate-processes/tobac/blob/730fa9affc0b6e7d3facf525faf73cc3a6406e74/tobac/analysis.py#L310

Should be:
if len(area.shape)==3:
    area_feature=np.sum(area[0]*(mask_i_surface.data>0))
elif len(area.shape)==2:
    area_feature=np.sum(area*(mask_i_surface.data>0))

Or it will be the sum of all time dimensions.

**Comment by freemansw1** [comment]
I've marked this as a bug for now while we investigate. I don't have a ton of experience with the analysis code, but at first glance it does not look like a bug to me. `area` is set above: 
https://github.com/climate-processes/tobac/blob/d97517c3fd5af99defbb9fa5a9b924db37f6500d/tobac/analysis.py#L286

and is correctly a 2D variable with X and Y dimensions. Again, I'm not as familiar with the analysis code, so I'm happy to be wrong here.

**Comment by freemansw1** [comment]
I'm going to close this as there appears to not be a bug here. Happy to reopen if I'm missing something,  @huangynj .
