### ISSUE TITLE
DOC: Update README.MD to reflect TOBAC is not just for clouds

### ISSUE THREAD

**Issue by scollis** [tobac-project/tobac#58]
First, I am not suggesting a name change. I worry that folks might be dissuaded from using for radar based objects and other objects by the description. Once TINT is fully integrated (TINT Is Now TOBAC) we should update the readme. We can add some narrative like "Initially designed to track clouds, TOBAC is now used to track a variety of objects in datasets including..... "

**Comment by freemansw1** [comment]
I've opened #197 to address this. You're totally right that we should encourage users to use *tobac* for all sorts of meteorological phenomena. Thanks for the issue, @scollis !

**Comment by freemansw1** [comment]
This has been merged and will be resolved in v1.4.0.
